apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: result
  name: result
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 80
  - name: "5858"
    port: 5858
    targetPort: 5858
  selector:
    io.kompose.service: result
status:
  loadBalancer: {}
