apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: result
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: result
    spec:
      containers:
      - args:
        - nodemon
        - --debug
        - server.js
        image: result
        imagePullPolicy: ""
        name: result
        ports:
        - containerPort: 80
        - containerPort: 5858
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: result-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: result-claim0
        persistentVolumeClaim:
          claimName: result-claim0
status: {}
